# Welcome to Jekyll!
#
# ...

# Site settings
title: "PEA 2 DE MIRIAM YUPA QUISPE"
email: "yupaquispe3@gmail.com"
description: >
  Bienvenido a mi sitio, donde comparto mis pensamientos y proyectos.
  Soy una estudiante entusiasta del VI Ciclo del Instituto SISE,
  dedicada al estudio y desarrollo en el campo de Software y Sistemas.
  Mi pasión por la tecnología y el aprendizaje continuo me impulsa
  a buscar oportunidades para mejorar mis habilidades y adquirir
  experiencia práctica en el área.
baseurl: ""  # the subpath of your site, e.g. /blog
url: "https://miriamyupa.github.io"      # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: "@Miriam60903033"
github_username: "MiriamYupaQuispe"

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# ...
